### ISSUE TITLE
“子元素定位从而导致父元素塌陷”的现象

### ISSUE THREAD

**Issue by swpuLeo** [swpuLeo/JavaScriptComponents#1]
## 现象的产生

在练习这个点击效果时，产生这样一个现象：点击 `body` 元素并未出现预想的点击效果，IDE 和 控制台并未报错；当点击图片所在区域时才产生点击效果。

检查元素 `body` 高度塌陷。但是为什么点击效果又能在图片所在区域产生？

**Comment by swpuLeo** [comment]
下面是点击效果的 jQuery 实现代码：
```js
var a_idx = 0;
$(document).ready(function ($) {
    $('body').click(function(e){
        var a = ['富强', '民主', '文明', '和谐', '自由', '平等', '公正', '法治', '爱国', '敬业', '诚信', '友善'];
        var $i = $('<span></span>').text(a[a_idx]);
        a_idx = (a_idx + 1) % a.length;
        var x = e.pageX,
            y = e.pageY;
        $i.css({
            "z-index": 999,
            "top": y - 20,
            "left": x,
            "position": "absolute",
            "font-weight": "bold",
            "color": "#ff6651"
        });
        $('body').append($i);
        $i.animate({
            "top": y - 180,
            "opacity": 0
        }, 1500, function(){
            $i.remove();
        });
    });
});
```

**Comment by swpuLeo** [comment]
从 jQuery 实现代码来看，创建的 `span` 元素被设置为绝对定位 `position: absolute;`。并且，`span` 元素是直接插入 `body` 元素的 - `$('body').append($i);`

**Comment by swpuLeo** [comment]
下面是 css 代码：
```css
@charset "utf-8";

div {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 400px;
    height: 300px;
}
img {
    width: 100%;
    height: auto;
}
```
